import { useState } from "react";
import axios from "axios";

const baseURL = "http://localhost:3000/";
const isDevelopment = process.env.NODE_ENV === "development";

export default function AddTurbineForm() {
  const [inputs, setInputs] = useState({});

  const handleChange = (event) => {
    const name = event.target.name;
    const value = event.target.value;
    setInputs((values) => ({ ...values, [name]: value }));
  };

  const handleSubmit = (event) => {
    event.preventDefault();

    console.log(inputs);

    axios.post('/turbine', inputs)
      .then(function (response) {
        console.log(response);
      })
      .catch(function (error) {
        console.log(error);
      });
  };

  return (
    <form onSubmit={handleSubmit}>
      <label>
        Turbine name:
        <input
          type="text"
          name="name"
          value={inputs.name || ""}
          onChange={handleChange}
        />
      </label>
      <label>
        Turbine capacity? (in MW):
        <input
          type="number"
          name="capacity"
          value={inputs.capacity || ""}
          onChange={handleChange}
        />
      </label>
      <label>
        Coords latitude:
        <input
          type="number"
          name="coords_lat"
          value={inputs.coords_lat || ""}
          onChange={handleChange}
        />
      </label>
      <label>
        Coords longitude:
        <input
          type="number"
          name="coords_long"
          value={inputs.coords_long || ""}
          onChange={handleChange}
        />
      </label>
      <label>
        Status:
        <select
          name="status"
          value={inputs.status || ""}
          onChange={handleChange}
        >
          <option value="Active">Active</option>
          <option value="Inactive">Inactive</option>
        </select>
      </label>
      <label>
        Last inspection:
        <input
          type="date"
          name="lastInspection"
          value={inputs.lastInspection || ""}
          onChange={handleChange}
        />
      </label>
      <input type="submit" />
    </form>
  );
}

// {
//   id: 1,                                  // This is generated by the server
//   name: "Mock Turbine 1",        
//   site: "A serious wind site",          // This is a foreign key
//   siteId: 1,                           // This is a foreign key
//   capacity: 8, // in MW 
//   location: "Location 1",               // This is generated by the server
//   coords_lat: 51.598221,
//   coords_long: 1.79009,
//   status: "Active",
//   lastInspection: "2021-01-01",
// },

// Dis is what we get when we submit the form
// {
//     "name": "sfgeg",
//     "capacity": "22",
//     "coords_lat": "2.22",
//     "coords_long": "2.22",
//     "lastInspection": "2025-01-08"
// }

