import { useState } from "react";
import axios from "axios";
import { useForm } from "react-hook-form";

const baseURL = "http://localhost:3000/";
const isDevelopment = process.env.NODE_ENV === "development";

export default function AddTurbineForm() {
  const [inputs, setInputs] = useState({});

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors },
  } = useForm();

  console.log(errors);

  const onSubmit = (data) => console.log(data);

  // const onSubmit = (event) => {
  //   event.preventDefault();

  //   axios.post(baseURL + 'turbine', inputs)
  //     .then(function (response) {
  //       console.log(response);
  //     })
  //     .catch(function (error) {
  //       console.log(error);
  //     });
  // };

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <label>
        Turbine name:
        <input type="text" {...register("name", { required: "This is required" })} />
      </label>
      <label>
        Turbine capacity? (in MW):
        <input type="number" {...register("capacity", { required: "This is required", min: { value: 0, message: 'Value must be greater than 0'} })} />
      </label>
      <label>
        Coords latitude:
        <input type="number" step="any" {...register("coords_lat", { required: "This is required" })} />
      </label>
      <label>
        Coords longitude:
        <input type="number" step="any" {...register("coords_long", { required: "This is required" })} />
      </label>
      <label>
        Last inspection:
        <input
          type="date"
          placeholder="lastInspection"
          {...register("lastInspection", { required: "This is required" })}
        />
      </label>
      <label>
        Status:
        <select {...register("status", { required: true })}>
          <option value="Active">Active</option>
          <option value="Inactive">Inactive</option>
        </select>
      </label>
      <input type="submit" />
    </form>
  );
}

// {
//   id: 1,                                  // This is generated by the server
//   name: "Mock Turbine 1",
//   site: "A serious wind site",          // This is a foreign key
//   siteId: 1,                           // This is a foreign key
//   capacity: 8, // in MW
//   location: "Location 1",               // This is generated by the server
//   coords_lat: 51.598221,
//   coords_long: 1.79009,
//   status: "Active",
//   lastInspection: "2021-01-01",
// },

// Dis is what we get when we submit the form
// {
//     "name": "sfgeg",
//     "capacity": "22",
//     "coords_lat": "2.22",
//     "coords_long": "2.22",
//     "lastInspection": "2025-01-08"
// }
